# Generated by Django 2.2.11 on 2020-04-14 14:03

import app_data.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Категирия',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='DailyFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Променено на')),
            ],
            options={
                'verbose_name': 'Храна',
                'verbose_name_plural': 'Обедно меню',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FoodsAppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
            ],
            options={
                'verbose_name': 'Настройки на приложението',
                'verbose_name_plural': 'Настройки на приложението',
                'abstract': False,
                'unique_together': {('type', 'namespace')},
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заглавие')),
                ('text', models.TextField(verbose_name='Текст')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Създадено на')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Променено на')),
                ('image', models.ImageField(upload_to='')),
                ('category_food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food', to='foods.CategoryFood')),
            ],
            options={
                'verbose_name': 'Храна',
                'verbose_name_plural': 'Храни',
                'ordering': ('-created_at',),
            },
        ),
    ]
