# Generated by Django 2.2.11 on 2020-04-18 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyfood',
            name='category_food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dailyfood', to='foods.CategoryFood'),
        ),
    ]
