# Generated by Django 2.2.11 on 2020-04-01 14:52

import app_data.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('namespace', models.CharField(default=None, max_length=100, unique=True, verbose_name='Instance namespace')),
                ('app_data', app_data.fields.AppDataField(default='{}', editable=False)),
            ],
            options={
                'verbose_name': 'Apphook config',
                'verbose_name_plural': 'Apphook configs',
                'abstract': False,
                'unique_together': {('type', 'namespace')},
            },
        ),
    ]
