# Generated by Django 2.2.11 on 2020-04-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='declaration_gdpr',
            field=models.BooleanField(default=False, verbose_name='Съгласен съм с'),
        ),
        migrations.AddField(
            model_name='order',
            name='declaration_site',
            field=models.BooleanField(default=False, verbose_name='Съгласен съм с'),
        ),
    ]
