# Generated by Django 2.2.11 on 2020-04-08 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200401_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.EmailField(blank=True, max_length=250, verbose_name='Адрес'),
        ),
    ]
